version: '3.8'

services:
  test-db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: thaitoan2311
      MYSQL_DATABASE: ecommerce_test
      MYSQL_ROOT_HOST: '%'

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    command: npm test
    environment:
      - NODE_ENV=test
      - DB_HOST=test-db
      - DB_USER=root
      - DB_PASSWORD=thaitoan2311
      - DB_NAME=ecommerce_test
    depends_on:
      - test-db