openapi: 3.0.0

info:
  title: E-commerce API
  description: This API provides endpoints for managing products in an E-commerce system.
  version: 2.0.0

servers:
  - url: https://localhost:3000/api/v2

tags:
  - name: Authentication
    description: Endpoints related to user authentication and authorization.

  - name: User Products
    description: Endpoints for managing user-specific product interactions.

  - name: User Categories
    description: Endpoints for managing user-specific category interactions.

  - name: User Cart
    description: Endpoints for managing user shopping carts.

  - name: User Orders
    description: Endpoints for managing user orders.

  - name: Admin Products
    description: Endpoints for managing product data, variants, images and categories.

  - name: Admin Variants
    description: Endpoints for managing variants.

  - name: Admin Categories
    description: Endpoints for managing categories.

  - name: Admin Coupons
    description: Endpoints for managing discount coupons.

  - name: Admin Attributes
    description: Endpoints for managing attributes.


paths:
  # Authentication
  /auth/signin:
    $ref: ./paths/index.paths.yaml#/signin

  /auth/signup:
    $ref: ./paths/index.paths.yaml#/signup

  /auth/refreshToken:
    $ref: ./paths/index.paths.yaml#/refresh

  /auth/refreshToken/reset:
    $ref: ./paths/index.paths.yaml#/resetToken

  # User Products
  /products:
    $ref: ./paths/index.paths.yaml#/userProducts
  
  /products/{productID}:
    $ref: ./paths/index.paths.yaml#/userProduct

  /products/{productID}/variants:
    $ref: ./paths/index.paths.yaml#/userProductVariants

  /products/{productID}/images:
    $ref: ./paths/index.paths.yaml#/userProductImages

  /products/{productID}/categories:
    $ref: ./paths/index.paths.yaml#/userProductCategories

  # User Categories
  /categories:
    $ref: ./paths/index.paths.yaml#/userCategories

  /categories/{categoryName}:
    $ref: ./paths/index.paths.yaml#/userCategory

  /categories/{categoryName}/ascendants:
    $ref: ./paths/index.paths.yaml#/userAscendantCategories

  /categories/{categoryName}/descendants:
    $ref: ./paths/index.paths.yaml#/userDescendantCategories

  # User Cart
  /cart:
    $ref: ./paths/index.paths.yaml#/userCart

  /cart/items:
    $ref: ./paths/index.paths.yaml#/userCartItems

  /cart/items/{variantID}:
    $ref: ./paths/index.paths.yaml#/userCartItemsVariant

  # User Order
  /orders:
    $ref: ./paths/index.paths.yaml#/userOrders
  
  /orders/{orderID}:
    $ref: ./paths/index.paths.yaml#/userOrder
  
  /orders/pending:
    $ref: ./paths/index.paths.yaml#/userPendingOrder

  /orders/pending/coupons:
    $ref: ./paths/index.paths.yaml#/userPendingCoupon

  # Admin Products
  /admin/products:
    $ref: ./paths/index.paths.yaml#/adminProducts

  /admin/products/{productID}:
    $ref: ./paths/index.paths.yaml#/adminProduct

  # Admin Products Variants

  /admin/products/{productID}/variants:
    $ref: ./paths/index.paths.yaml#/adminProductVariants

  /admin/products/{productID}/variants/{variantID}:
    $ref: ./paths/index.paths.yaml#/adminProductVariant

  # Admin Products Images
  /admin/products/{productID}/images:
    $ref: ./paths/index.paths.yaml#/adminProductImages

  /admin/products/{productID}/images/{imageID}:
    $ref: ./paths/index.paths.yaml#/adminProductImage

  # Admin Products Categories

  /admin/products/{productID}/categories:
    $ref: ./paths/index.paths.yaml#/adminProductCategories

  /admin/products/{productID}/categories/{categoryName}:
    $ref: ./paths/index.paths.yaml#/adminProductCategory

  # Admin Variants

  /admin/variants:
    $ref: ./paths/index.paths.yaml#/adminVariants

  /admin/{variantID}:
    $ref: ./paths/index.paths.yaml#/adminVariant

  # Admin Categories

  /admin/categories:
    $ref: ./paths/index.paths.yaml#/adminCategories

  /admin/categories/{categoryName}:
    $ref: ./paths/index.paths.yaml#/adminCategory

  # Admin Coupons

  /admin/coupons:
    $ref: ./paths/index.paths.yaml#/adminCoupons

  /admin/coupons/{couponID}:
    $ref: ./paths/index.paths.yaml#/adminCoupon

  /admin/coupons/{couponID}/categories:
    $ref: ./paths/index.paths.yaml#/adminCouponCategories

  /admin/coupons/{couponID}/products:
    $ref: ./paths/index.paths.yaml#/adminCouponProducts

  # Admin Attributes

  /admin/attributes:
    $ref: ./paths/index.paths.yaml#/adminAttributes

  /admin/attributes/{attributeID}:
    $ref: ./paths/index.paths.yaml#/adminAttribute

  /admin/attributes/{attributeID}/values/{valueID}:
    $ref: ./paths/index.paths.yaml#/adminAttributeValues

  /admin/attributes/{attributeID}/variants:
    $ref: ./paths/index.paths.yaml#/adminAttributeVariants
    
  # Admin Users

  /admin/users:
    $ref: ./paths/index.paths.yaml#/adminUsers

  /admin/users/{userID}:
    $ref: ./paths/index.paths.yaml#/adminUser

  /admin/users/{userID}/cart:
    $ref: ./paths/index.paths.yaml#/adminUserCart

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    error400:
      $ref: ./schemas/error/error400.yaml
    error401:
      $ref: ./schemas/error/error401.yaml
    error403:
      $ref: ./schemas/error/error403.yaml
    error404:
      $ref: ./schemas/error/error404.yaml
    error500:
      $ref: ./schemas/error/error500.yaml
      
    product:
      $ref: ./schemas/products/product.yaml
    variantForUser:
      $ref: ./schemas/products/variantForUser.yaml
    variantForAdmin:
      $ref: ./schemas/products/variantForAdmin.yaml
    variantAttribute: 
      $ref: ./schemas/products/variantAttribute.yaml
    image:
      $ref: ./schemas/products/image.yaml
    categoryNames:
      $ref: ./schemas/products/categoryNames.yaml
    category:
      $ref: ./schemas/products/category.yaml
    attribute:
      $ref: ./schemas/products/attribute.yaml
    value:
      $ref: ./schemas/products/value.yaml
    coupon:
      $ref: ./schemas/shopping/coupon.yaml
    order:
      $ref: ./schemas/shopping/order.yaml
    user:
      $ref: ./schemas/users/user.yaml
    address:
      $ref: ./schemas/users/address.yaml
    timestamps:
      $ref: ./schemas/timestamps.yaml
    pagination:
      $ref: ./schemas/pagination.yaml