# DELETE /admin/attributes/{attributeID}/values/{valueID}
tags:
  - Admin Attributes
summary: Delete attribute value
description: Deletes a specific attribute value. 
  This action will remove the value from the attribute and any associated product variants.
security:
  - bearerAuth: []
parameters:
  - name: attributeID
    in: path
    description: Attribute ID
    required: true
    schema:
      type: string
      example: "1"
  - name: valueID
    in: path
    description: Value ID
    required: true
    schema:
      type: string
      example: "1"
responses:
  200:
    description: Attribute value deleted
    content:
      application/json:
        schema:
          type: object
          properties:
            success:
              type: boolean
              example: true
  401:
    description: Token invalid, not authenticated
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error401.yaml"
  403:
    description: Not an admin
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error403.yaml"
  404:
    description: Attribute Value Not Found
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error404.yaml"
  409:
    description: Attribute Value in Use
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error409.yaml"
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error500.yaml"