# GET /admin/attributeValues:
tags:
  - Admin Attribute Values
summary: Get attribute values
description: Retrieves a list of all attribute values. <br>
  Support pagination, sorting and filtering. <br>
  If `sort` is not provided, the default sort is by `createdAt` in descending order.
security:
  - bearerAuth: []
parameters:
  - name: page
    in: query
    description: Page to retrieve
    required: false
    schema:
      type: integer

  - name: size
    in: query
    description: Size each page
    required: false
    schema:
      type: integer

  - name: valueID
    in: query
    description: Filter by valueID. <br> 
      For more information, see the [Query String](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#query-string).
    required: false
    schema:
      example: "[like]1"
  
  - name: value
    in: query
    description: Filter by value. <br> 
      For more information, see the [Query String](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#query-string).
    required: false
    schema:
      example: "[like]value"

  - name: attributeID
    in: query
    description: Filter by attributeID. <br> 
      For more information, see the [Query String](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#query-string).
    required: false
    schema:
      example: "[like]1"

  - name: attributeName
    in: query
    description: Filter by attribute name. <br> 
      For more information, see the [Query String](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#query-string).
    required: false
    schema:
      example: "[like]attribute"

  - name: createdAt
    in: query
    description: Filter by created time. <br> 
      For more information, see the [Query Date](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#date-filtering).
    required: false
    schema:
      example: "[gte]2024-01-01"

  - name: updatedAt
    in: query
    description: Filter by updated time. <br> 
      For more information, see the [Query Date](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#date-filtering).
    required: false
    schema:
      example: "[gte]2024-01-01"

  - name: sort
    in: query
    required: false
    description: |
      Sort by attribute values' fields. <br> 
      Support fields: `valueID`, `attributeID`, `value`, `createdAt`, `updatedAt`. <br>
      For more information, see the [Sorting](http://github.com/Tondeptrai23/e-commerce-api/blob/main/src/v2/document/docs/query.md#sorting).
    schema:
      example: "value,-attributeID"
responses:
  200:
    description: Attribute values found
    content:
      application/json:
        schema:
          type: object
          properties:
            success:
              type: boolean
              example: true
            values:
              type: array
              items:
                type: object
                allOf:
                  - $ref: "../../../schemas/products/value.yaml"
                  - $ref: "../../../schemas/timestamps.yaml"
          allOf:
            - $ref: "../../../schemas/pagination.yaml"
  400:
    description: Invalid request parameters
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error400.yaml"
  401:
    description: Token invalid, not authenticated
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error401.yaml"
  403:
    description: Not an admin
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error403.yaml"
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          $ref: "../../../schemas/error/error500.yaml"  
